W5D1/music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :bands do
    resources :albums, only: [:new]
  end
  resources :albums, except: [:index, :new] do
    resources :tracks, only: [:new]
  end
  resources :tracks, except: [:index, :new]

  root to: "users#new"
end

W5D1/music_app/app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  year       :integer          not null
#  band_id    :integer          not null
#  live       :boolean          default(FALSE)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Album < ApplicationRecord

  validates :title, presence: true
  validates :year, presence: true
  validates :band_id, presence: true
  validates :live, presence: true

  belongs_to :band,
    class_name: :Band,
    foreign_key: :band_id

  has_many :tracks,
    class_name: :Track,
    foreign_key: :album_id,
    dependent: :destroy
end

W5D1/music_app/app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ApplicationRecord
  validates :name, presence: true

  has_many :albums,
    class_name: :Album,
    foreign_key: :band_id,
    dependent: :destroy

  has_many :tracks,
    class_name: :Track,
    foreign_key: :band_id,
    dependent: :destroy
end

W5D1/music_app/app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id         :integer          not null, primary key
#  album_id   :integer          not null
#  band_id    :integer          not null
#  title      :string           not null
#  ord        :integer          not null
#  lyrics     :text
#  bonus      :boolean          default(FALSE)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Track < ApplicationRecord

  validates :album_id, presence: true
  validates :band_id, presence: true
  validates :title, presence: true
  validates :ord, presence: true
  validates :bonus, presence: true

  belongs_to :album,
    class_name: :Album,
    foreign_key: :album_id

  belongs_to :band,
    class_name: :Band,
    foreign_key: :band_id

end

W5D1/music_app/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord

  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }

  after_initialize :ensure_session_token

  attr_reader :password

  def self.generate_session_token
    SecureRandom::urlsafe_base64
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    password_hash = BCrypt::Password.new(self.password_digest)
    password_hash.is_password?(password)
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end
end

W5D1/music_app/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :require_logged_in, only: [:new, :create, :edit, :update, :destroy]

  def new
    @album = Album.new
    @bands = Band.all
    @band = Band.find(params[:band_id])
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to album_url(@album)
    else
      flash[:errors] = @album.errors.full_messages
      render :new
    end
  end

  def edit
    @album = Album.find(params[:id])
  end

  def update
    @album = Album.find(params[:id])
    if @album.update(album_params)
      redirect_to album_url(@album)
    else
      flash[:errors] = @album.errors.full_messages
      render :edit
    end
  end

  def show
    @album = Album.find(params[:id])
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy
  end

  private
  def album_params
    params.require(:album).permit(:title, :year, :band_id, :live)
  end
end

W5D1/music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?


  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def login!(user)
    session[:session_token] = user.session_token
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def logged_in?
    !current_user.nil?
  end

  def require_logged_in
    redirect_to new_session_url unless logged_in?
  end

  def require_logged_out
    redirect_to bands_url if logged_in?
  end
end

W5D1/music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :require_logged_in, only: [:new, :create, :edit, :update]

  def index
    @bands = Band.all
  end

  def new
    @band = Band.new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band)
    else
      flash[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @band = Band.find(params[:id])
  end

  def edit
    @band = Band.find(params[:id])
  end

  def update
    @band = Band.find(params[:id])
    if @band.update(band_params)
      redirect_to band_url(@band)
    else
      flash[:errors] = @user.errors.full_messages
      render :edit
    end
  end

  def destroy
    @band = Band.find(params[:id])
    @band.destroy
    redirect_to bands_url
  end

  private
  def band_params
    params.require(:band).permit(:name)
  end
end

W5D1/music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_logged_out, only: [:create, :new]

  def new
  end

  def create
    user = User.find_by_credentials(params[:user][:email], params[:user][:password])

    if user.nil?
      flash.now[:errors] = ["Incorrect email and/or password"]
      render :new
    else
      login!(user)
      redirect_to bands_url
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end
end

W5D1/music_app/app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :require_logged_in, only: [:new, :create, :edit, :update, :destroy]

  def new
    @track = Track.new
  end

  def create
    @track = Track.new(track_params)
    if @track.save
      redirect_to track_url(@track)
    else
      flash[:errors] = @track.errors.full_messages
      render :new
    end
  end

  def edit
    @track = Track.find(params[:id])
  end

  def update
    @track = Track.find(params[:id])
    if @track.update(track_params)
      redirect_to track_url(@track)
    else
      flash[:errors] = @track.errors.full_messages
      render :edit
    end
  end

  def show
    @track = Track.find(params[:id])
  end

  def destroy
    @track = Track.find(params[:id])
    @track.destroy
  end

  private
  def track_params
    params.require(:track).permit(:album_id, :band_id, :title, :ord, :lyrics, :bonus)
  end
end

W5D1/music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_logged_out
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login!(@user)
      redirect_to bands_url
    else
      flash[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

W5D1/music_app/app/helpers/albums_helper.rb
module AlbumsHelper
end

W5D1/music_app/app/helpers/bands_helper.rb
module BandsHelper
end

W5D1/music_app/app/helpers/sessions_helper.rb
module SessionsHelper
end

W5D1/music_app/app/helpers/tracks_helper.rb
module TracksHelper
end

W5D1/music_app/app/helpers/users_helper.rb
module UsersHelper
end

W5D1/music_app/app/views/albums/edit.html.erb
<h1>Albums#edit</h1>
<p>Find me in app/views/albums/edit.html.erb</p>

W5D1/music_app/app/views/albums/new.html.erb
<h1>Create New Album for <%= @band.name %></h1>

<form class="" action="<%= albums_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="title">Title</label>
  <input type="text" name="album[title]" value="">

  <select class="" name="album[year]">
    <option value="">
      <% @bands.each do |band| %>
        <%= band.name %>
      <% end %>
    </option>
  </select>

  <input type="submit" name="" value="Submit">
</form>

W5D1/music_app/app/views/albums/show.html.erb
<h1>Albums#show</h1>
<p>Find me in app/views/albums/show.html.erb</p>

W5D1/music_app/app/views/bands/edit.html.erb
<h1>Bands#edit</h1>
<p>Find me in app/views/bands/edit.html.erb</p>

W5D1/music_app/app/views/bands/index.html.erb
<h2>Spot any of your Favorite Bands?</h2>

<%= link_to "Create Band", new_band_url, method: :get %>

<% @bands.each do |band| %>
  <ul>
    <li><h3><%= band.name %></h3></li>
      <%= link_to 'Band Page', band_url(band), method: :get %>
      <%= link_to 'Destroy Band', band_url(band), method: :delete %>
  </ul>
  <br>
<% end %>

W5D1/music_app/app/views/bands/new.html.erb
<h2>Create Your Favorite Band</h2>

<form class="" action="<%= bands_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="name">Name</label>
  <input type="text" name="band[name]" value="">

  <input type="submit" name="" value="Submit">
</form>

W5D1/music_app/app/views/bands/show.html.erb
<h1><%= @band.name %></h1>

<%= link_to 'Home Page', bands_url, method: :get %>
<br>
<br>
<%= link_to 'Create Album', new_band_album_url(@band), method: :get %>

W5D1/music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="top-buttons">
      <% if logged_in? %>
      <%= button_to "Log Out", session_url, method: :delete, class: 'log-out-button' %>
      <% else %>
      <%= button_to "Sign Up", new_user_url, method: :get, class: 'sign-up-button' %>
      <%= button_to "Log In", new_session_url, method: :get, class: 'log-in-button' %>
      <% end %>
    </div>
    <br>
    <br>
    <% if flash[:errors] %>
    <h3>Errors:</h3>
      <% flash[:errors].each do |error| %>
        <ul>
          <li><%= error %></li>
        </ul>
      <% end %>
    <% end %>
    <%= yield %>
  </body>
</html>

W5D1/music_app/app/views/tracks/edit.html.erb
<h1>Tracks#edit</h1>
<p>Find me in app/views/tracks/edit.html.erb</p>

W5D1/music_app/app/views/tracks/new.html.erb
<h1>Tracks#new</h1>
<p>Find me in app/views/tracks/new.html.erb</p>

W5D1/music_app/app/views/tracks/show.html.erb
<h1>Tracks#show</h1>
<p>Find me in app/views/tracks/show.html.erb</p>

W5D1/music_app/app/views/users/new.html.erb
<h2>Sign Up Page</h2>

<form class="" action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label for="">Email</label>
  <input type="text" name="user[email]" value="" placeholder="Email">
  <br>
  <br>
  <label for="">Password</label>
  <input type="password" name="user[password]" value="" placeholder="Password">
  <br>
  <br>
  <input type="submit" name="" value="Submit">

</form>